# Generated by Django 3.1.1 on 2020-10-07 16:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Title', models.CharField(max_length=200)),
                ('project_Image', models.ImageField(upload_to='images/')),
                ('project_Year', models.CharField(max_length=4)),
                ('project_Institute', models.CharField(max_length=200)),
                ('project_Type', models.CharField(max_length=200)),
                ('project_Description', ckeditor.fields.RichTextField()),
                ('project_Link', models.URLField()),
                ('project_Skills', models.ManyToManyField(to='Global.Skills')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
