# Generated by Django 3.1.1 on 2020-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_Name', models.CharField(max_length=200)),
                ('file_Upload', models.FileField(upload_to='files/')),
                ('file_Icon', models.CharField(max_length=200)),
                ('file_Description', models.CharField(max_length=200)),
                ('file_Type', models.CharField(choices=[('--', '--'), ('docx', 'docx'), ('pdf', 'pdf'), ('xlsx', 'xlsx'), ('pptx', 'pptx')], default='--', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Files',
                'ordering': ['file_Name'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_Type', models.CharField(choices=[('Technical', 'Technical'), ('Soft', 'Soft'), ('Other', 'Other')], max_length=100)),
                ('skill_Category', models.CharField(choices=[('Admin', 'Admin'), ('Back-End', 'Back-End'), ('Databases', 'Databases'), ('DevOps', 'DevOps'), ('Front-End', 'Front-End'), ('General', 'General'), ('Leadership', 'Leadership'), ('Projects', 'Projects'), ('Software', 'Software'), ('Systems', 'Systems'), ('Web App Dev', 'Web App Dev')], max_length=100)),
                ('skill_Name', models.CharField(max_length=100)),
                ('skill_Icon', models.CharField(max_length=100)),
                ('skill_Description', models.TextField(max_length=500)),
                ('skill_Years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_Level', models.CharField(choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Advanced', 'Advanced')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['-skill_Years'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_Link', models.CharField(max_length=200)),
                ('social_SiteName', models.CharField(max_length=200)),
                ('social_FaClass', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_Name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['tag_Name'],
            },
        ),
    ]
