# Generated by Django 3.1.1 on 2020-10-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_Name', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'ordering': ['file_Name'],
            },
        ),
    ]
