# Generated by Django 3.1.1 on 2021-01-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_Type',
            field=models.CharField(choices=[('--', '--'), ('docx', 'docx'), ('pdf', 'pdf'), ('xlsx', 'xlsx'), ('pptx', 'pptx'), ('image', 'image')], default='--', max_length=20),
        ),
    ]
