# Generated by Django 3.1.1 on 2020-10-01 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_Upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file_Name',
            field=models.CharField(max_length=200),
        ),
    ]
