# Generated by Django 3.1.1 on 2020-10-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0003_auto_20201001_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_Link', models.CharField(max_length=200)),
                ('social_SiteName', models.CharField(max_length=200)),
                ('social_FaClass', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
