# Generated by Django 3.1.1 on 2020-10-02 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0004_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_Icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
