# Generated by Django 3.1.1 on 2020-10-03 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0005_files_file_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_Description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
