# Generated by Django 3.1.1 on 2020-10-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0006_files_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_Type',
            field=models.CharField(choices=[('--', '--'), ('Word', 'docx'), ('PDF', 'pdf'), ('Excel', 'xlsx'), ('PowerPoint', 'pptx')], default='--', max_length=20),
        ),
    ]
