# Generated by Django 3.1.1 on 2020-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0007_files_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_Type',
            field=models.CharField(choices=[('--', '--'), ('docx', 'docx'), ('pdf', 'pdf'), ('xlsx', 'xlsx'), ('pptx', 'pptx')], default='--', max_length=20),
        ),
    ]
