# Generated by Django 3.1.1 on 2020-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_pub_date', models.DateTimeField()),
                ('post_author', models.CharField(max_length=200)),
                ('post_image', models.ImageField(upload_to='images/')),
                ('post_body', models.TextField()),
                ('post_mod_date', models.DateTimeField()),
                ('post_tags', models.CharField(max_length=200)),
            ],
        ),
    ]
