# Generated by Django 3.1.1 on 2020-09-29 16:17

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
