# Generated by Django 3.1.1 on 2020-09-30 03:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200929_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_Name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['tag_Name'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_tags',
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(to='Blog.Tags'),
        ),
    ]
