# Generated by Django 3.1.1 on 2021-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='artifact_Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
