# Generated by Django 3.1.1 on 2020-10-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artifacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artifacts',
            new_name='Artifact',
        ),
    ]
