# Generated by Django 3.1.1 on 2020-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
        ('Artifacts', '0002_auto_20201001_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='artifacts_Skills',
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifacts_Skills',
            field=models.ManyToManyField(to='Global.Tags'),
        ),
    ]
