# Generated by Django 3.1.1 on 2020-10-01 15:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artifacts', '0003_auto_20201001_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifacts_Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
