# Generated by Django 3.1.1 on 2020-10-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0003_auto_20201001_1743'),
        ('Artifacts', '0004_auto_20201001_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='artifacts_Files',
            field=models.ManyToManyField(to='Global.Files'),
        ),
    ]
