# Generated by Django 3.1.1 on 2020-10-18 20:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education_Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
