# Generated by Django 3.1.1 on 2020-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_Courses',
            field=models.ManyToManyField(to='Education.Courses'),
        ),
    ]
