# Generated by Django 3.1.1 on 2020-10-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0009_skills'),
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education_Skills',
        ),
        migrations.AddField(
            model_name='education',
            name='education_Skills',
            field=models.ManyToManyField(to='Global.Skills'),
        ),
    ]
