# Generated by Django 3.1.1 on 2020-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Education', '0001_initial'),
        ('Global', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_Image', models.ImageField(upload_to='images/')),
                ('experience_Employer', models.CharField(max_length=200)),
                ('experience_Title', models.CharField(max_length=200)),
                ('experience_Title_Abbr', models.CharField(max_length=100, null=True)),
                ('experience_Duration', models.CharField(max_length=200)),
                ('experience_DOH', models.DateField(null=True)),
                ('experience_DOL', models.DateField(blank=True, null=True)),
                ('experience_Summary', models.TextField(max_length=1000)),
                ('experience_Achievements', models.TextField(max_length=3000)),
                ('experience_Courses', models.ManyToManyField(blank=True, null=True, to='Education.Other')),
                ('experience_Skills', models.ManyToManyField(to='Global.Skills')),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['id'],
            },
        ),
    ]
