# Generated by Django 3.1.1 on 2020-10-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0009_skills'),
        ('Education', '0001_initial'),
        ('Experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_Courses',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_Courses',
            field=models.ManyToManyField(blank=True, null=True, to='Education.Other'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience_Skills',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_Skills',
            field=models.ManyToManyField(to='Global.Skills'),
        ),
    ]
